# tmux system clipboard fix for macOS
if-shell 'test "$(uname -s)" = Darwin' 'set-option -g default-command "exec reattach-to-user-namespace -l zsh"'

# 24 bit color support
# https://github.com/tmux/tmux/issues/34#issuecomment-241527745
set-option -ga terminal-overrides ",xterm-256color:Tc"

# act like vim
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# bind -r C-h select-window -t :-
# bind -r C-l select-window -t :+
# bind -t vi-copy 'v' begin-selection
# bind -t vi-copy 'V' rectangle-toggle
# bind -t vi-copy 'y' copy-selection

# act like GNU screen
set -g prefix C-a
bind C-a send-prefix
unbind C-b

# create new windows/panes in same directory
bind c new-window -c '#{pane_current_path}'
bind "\"" split-window -c '#{pane_current_path}'
bind % split-window -h -c '#{pane_current_path}'

# enable and disable keyboard input for panes

# size windows based on clients looking at that window
# setw -g aggressive-resize on
setw -g aggressive-resize off

# enable mouse control
# set -g mode-mouse on
set -g mouse on

# start window numbers at 1 to match keyboard order with tmux order
set -g base-index 1

# start pane numbers at 1 to match keyboard order with tmux order
setw -g pane-base-index 1

# easy resizing of panes
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5

# renumber windows sequentially after closing any of them
set -g renumber-windows on

# monitor windows for activity
setw -g monitor-activity on

# don't wait for escape sequences
set -sg escape-time 0

# display pane numbers for longer
set -g display-panes-time 2000

# remove administrative debris (time) in status bar
set -g status-left-length 50
set -g status-left ''
set -g status-right '%a, %b %d %H:%M'
# unread e-mail count
# set -ga status-right ' #[bg=brightblack,fg=cyan] 10 '

# centre window list
set -g status-justify centre

# increase scrollback lines
set -g history-limit 65536

# keybinding to clear history
bind C-k clear-history \; display-message "history cleared"

# Smart pane switching with awareness of vim splits
is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?)(diff)?$"'
bind -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"
bind -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"

bind C-l send-keys 'C-l'

# C-b ! breaks current pane into separate window
# join a pane/window from the current session into the current window
bind @ command-prompt -p "create pane from:" "join-pane -s ':%%'"

# reload the .tmux.conf file with Ctrl-r
bind C-r source-file ~/.tmux.conf \; display-message "configuration reloaded"

# toggle passthrough of prefix
bind P if-shell "[ \"$(tmux show-options -g prefix)\" = \"prefix C-a\" ]" 'set -g prefix C-b; display-message "passthrough enabled"; refresh-client -S' 'set -g prefix C-a; display-message "passthrough disabled"; refresh-client -S'

# show if we are in prefix mode
set -g  status-left '#{?client_prefix,#[fg=brightmagenta],}'
set -ga status-left '#H/#S'

# default statusbar colors
set -g status-style "bg=black,fg=white"
set -g message-style "bg=black,fg=brightmagenta"

# window indicators
setw -g window-status-style "fg=brightblack"
setw -g window-status-current-style "fg=brightgreen"
setw -g window-status-activity-style "bg=black,fg=brightblue"
setw -g window-status-bell-style "bg=black,fg=brightred"

# Allow local customization in ~/.tmux_local.conf
if-shell "[ -f ~/.tmux_local.conf ]" 'source ~/.tmux_local.conf'

# Swap space
#bind C-s if-shell "tmux find-window -N scratch" "last-window" "new-window -n scratch"
bind C-s swap-pane -t :scratch.1
